name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Siapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Capacitor
        run: npm install

      - name: Install Dependencies & Assets Tool
        run: |
          npm install
          npm install @capacitor/assets --save-dev

      - name: Generate Ikon dan Splash Screen
        run: |
          # Perintah ini akan mengambil icon.png dan splash.png 
          # lalu mengubahnya menjadi folder res di dalam proyek android
          npx capacitor-assets generate --android

      - name: Siapkan Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Suntik Izin Android (Permissions)
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />\n    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />\n    <uses-feature android:name="android.hardware.camera.ar" android:required="true" />' android/app/src/main/AndroidManifest.xml

      - name: Generate Folder Android & Sinkronisasi
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build APK Android
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload File APK
        uses: actions/upload-artifact@v4
        with:
          name: 3dAR-App-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
